version: 2.1

defaults: &defaults
  working_directory: ~/redisai-js
  docker:
    - image: circleci/node:10.16.3
    - image: redislabs/redisai:edge-cpu-bionic

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          no_output_timeout: 20m
          command: npm test

      - run:
          name: coverage
          command: npm run coverage

      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context:
            - common
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context:
            - common
