on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: get version from tag
        id: get_version
        run: |
            realversion="${GITHUB_REF/refs\/tags\//}"
            realversion="${realversion//v/}"
            echo "::set-output name=VERSION::$realversion"

      - name: Set version from tag
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: version
          value: ${{steps.get_version.outputs.VERSION}}

      - name: Read project name
        uses: notiz-dev/github-action-json-property@release
        id: get_package_json
        with:
          path: package.json
          prop_path: name

      - name: Read project version
        uses: notiz-dev/github-action-json-property@release
        id: get_package_version
        with:
          path: package.json
          prop_path: version

      - name: npm install
        run: npm install

      - name: publish to npm
        run: npm publish . --tag ${{steps.get_package_json.outputs.prop}}@${{steps.get_package_version.outputs.prop}}
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
