on:
  push:
#  release:
#    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: get version from tag
        id: get_version
        run: |
            realversion="155.155.155"
            echo "::set-output name=VERSION::$realversion"

      - name: Set version from tag
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: version
          value: ${{steps.get_version.outputs.VERSION}}

      - name: Read project name
        uses: notiz-dev/github-action-json-property@release
        id: get_package_json
        with:
          path: package.json
          prop_path: name

      - name: Read project version
        uses: notiz-dev/github-action-json-property@release
        id: get_package_version
        with:
          path: package.json
          prop_path: version

      - name: echo tag to be used
        run: echo ${{steps.get_package_json.outputs.prop}}@${{steps.get_package_version.outputs.prop}}

#      - name: publish to npm
#        run: npm publish . --tag ${{steps.get_package_json.outputs.prop}}@${{steps.get_package_version.outputs.VERSION}}
#        env:
#          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
